name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    
    - name: Install dependencies
      working-directory: server
      run: |
        if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
          npm ci
        else
          npm install
        fi
    
    - name: Run linting
      working-directory: server
      run: npm run lint --if-present
    
    - name: Run tests
      working-directory: server
      run: npm test --if-present

  build-and-deploy:
    name: Build and Deploy
    needs: lint-and-test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: server/package-lock.json
    
    - name: Install production dependencies
      working-directory: server
      run: |
        if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
          npm ci --production
        else
          npm install --production
        fi
    
    - name: Build application
      working-directory: server
      run: |
        npm run build --if-present
        # Create a basic build output if no build script exists
        mkdir -p build
        echo "Built at $(date)" > build/build-info.txt
    
    - name: Verify build output
      run: |
        echo "Current directory: $(pwd)"
        echo "Server directory contents:"
        ls -la server/ || true
        echo "Build directory contents:"
        ls -la server/build/ || true
        echo "Dist directory contents:"
        ls -la server/dist/ || true
        echo "Root directory contents:"
        ls -la
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: server-build
        path: |
          server/build/
          server/dist/
          server/output/
        if-no-files-found: warn
        retention-days: 5
    
    - name: Prepare static files
      run: |
        # Create directories if they don't exist
        mkdir -p assets
        mkdir -p images
        mkdir -p css
        mkdir -p js
        
        # List all files that will be included
        echo "Files to be uploaded:"
        find . -maxdepth 1 -type f -name "*.html" -o -name "*.xml" -o -name "*.txt" || true
        find assets/ -type f 2>/dev/null || echo "No files in assets/"
        find images/ -type f 2>/dev/null || echo "No files in images/"
        find css/ -type f 2>/dev/null || echo "No files in css/"
        find js/ -type f 2>/dev/null || echo "No files in js/"
    
    - name: Upload static files
      uses: actions/upload-artifact@v4
      with:
        name: static-assets
        path: |
          index.html
          assets/
          images/
          css/
          js/
          sitemap.xml
          robots.txt
        if-no-files-found: warn
        retention-days: 5
    
    - name: Deploy to production
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        echo "Deploying to production..."
        # Add your deployment commands here
        # For example, using rsync, scp, or a deployment service
        echo "Deployment completed!"